# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poluentes',
            fields=[
                ('pol_id', models.AutoField(primary_key=True, serialize=False)),
                ('pol_name', models.CharField(max_length=50)),
                ('pol_sigla', models.CharField(max_length=5)),
                ('pol_unidades', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Poluentes',
            },
        ),
    ]
