# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0002_poluentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poluentes',
            name='pol_unidades',
            field=models.CharField(max_length=15),
        ),
    ]
