# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0005_auto_20160329_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poluentes',
            old_name='pol_name',
            new_name='pol_nome',
        ),
    ]
