# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labqar', '0007_auto_20160411_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='lcl_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
