# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0008_local_lcl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poluentes',
        ),
        migrations.AlterField(
            model_name='campanha',
            name='cam_foto1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='cam_foto2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dados',
            name='cam_id',
            field=models.IntegerField(null=True, verbose_name='Campanha'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_10med',
            field=models.FloatField(null=True, verbose_name='Valor Etilbenzeno'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_10stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado Etilbenzeno'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_11med',
            field=models.FloatField(null=True, verbose_name='Valor MPXileno'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_11stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado MPXileno'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_12med',
            field=models.FloatField(null=True, verbose_name='Valor OXileno'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_12stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado OXileno'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_13med',
            field=models.FloatField(null=True, verbose_name='Valor partEnv'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_13stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado partEnv'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_14med',
            field=models.FloatField(null=True, verbose_name='Valor SO2offset'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_14stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado SO2offset'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_15med',
            field=models.FloatField(null=True, verbose_name='Valor Temp'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_15stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado Temp'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_16med',
            field=models.FloatField(null=True, verbose_name='Valor Hum %'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_16stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado Hum %'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_17med',
            field=models.FloatField(null=True, verbose_name='Valor Pressao'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_17stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado Pressao'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_18med',
            field=models.FloatField(null=True, verbose_name='Valor Rad'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_18stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado Rad'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_19med',
            field=models.FloatField(null=True, verbose_name='Valor Vel'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_19stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado Vel'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_1med',
            field=models.FloatField(null=True, verbose_name='Valor SO2'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_1stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado SO2'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_20med',
            field=models.FloatField(null=True, verbose_name='Valor Dir'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_20stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado Dir'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_2med',
            field=models.FloatField(null=True, verbose_name='Valor NO'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_2stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado NO'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_3med',
            field=models.FloatField(null=True, verbose_name='Valor NO2'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_3stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado NO2'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_4med',
            field=models.FloatField(null=True, verbose_name='Valor NOx'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_4stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado NOx'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_5med',
            field=models.FloatField(null=True, verbose_name='Valor CO'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_5stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado CO'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_6med',
            field=models.FloatField(null=True, verbose_name='Valor O3'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_6stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado O3'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_7med',
            field=models.FloatField(null=True, verbose_name='Valor Prec'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_7stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado Prec'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_8med',
            field=models.FloatField(null=True, verbose_name='Valor Benzeno'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_8stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado Benzeno'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_9med',
            field=models.FloatField(null=True, verbose_name='Valor Tolueno'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_9stat',
            field=models.SmallIntegerField(null=True, verbose_name='Estado Tolueno'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_data',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Data Recolha'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dad_p_aquisicao',
            field=models.IntegerField(null=True, verbose_name='P Aquisicao'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labqar.Estacao', verbose_name='Estacao'),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='est_foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='local',
            name='lcl_imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
