# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0013_auto_20160426_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo_campanha',
            name='cam_pm10',
            field=models.FloatField(blank=True, choices=[(1, b'Outro'), (1.18, b'Trafego'), (1.11, b'Fundo')], default=1, null=True),
        ),
    ]
