# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0014_periodo_campanha_cam_pm10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='lcl_imagem',
        ),
        migrations.AlterField(
            model_name='local',
            name='lcl_contacto',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Contacto'),
        ),
        migrations.AlterField(
            model_name='local',
            name='lcl_morada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Morada'),
        ),
        migrations.AlterField(
            model_name='local',
            name='lcl_nome',
            field=models.CharField(max_length=50, verbose_name=b'Nome'),
        ),
        migrations.AlterField(
            model_name='local',
            name='lcl_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Utilizador Associado'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='cat_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='labqar.Categoria'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_casas_decimais',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_codigo',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_conv_add',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_conv_mul',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_limiar',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_limite',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_limite_media',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_max_alarme',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_media_intervalo',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_media_tipo',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_min_alarme',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_nome',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_nome_completo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Nome a apresentar'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_perc_validacao_dia',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_perc_validacao_hora',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_tipo',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_unidade_apresent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Unidade de medicao'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_unidade_armaz',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='par_visivel',
            field=models.NullBooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='periodo_campanha',
            name='cam_data_final',
            field=models.DateTimeField(verbose_name=b'Data Fim'),
        ),
        migrations.AlterField(
            model_name='periodo_campanha',
            name='cam_data_inicio',
            field=models.DateTimeField(verbose_name=b'Data Inicio'),
        ),
        migrations.AlterField(
            model_name='periodo_campanha',
            name='cam_notas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Notas'),
        ),
        migrations.AlterField(
            model_name='periodo_campanha',
            name='cam_pm10',
            field=models.FloatField(blank=True, choices=[(1, b'Outro'), (1.18, b'Trafego'), (1.11, b'Fundo')], default=1, null=True, verbose_name=b'Factor PM10'),
        ),
    ]
