# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0015_auto_20160430_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='lcL_backgroud',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'Imagem de Fundo'),
        ),
        migrations.AlterField(
            model_name='periodo_campanha',
            name='cam_pm10',
            field=models.FloatField(choices=[(1, b'Outro'), (1.18, b'Trafego'), (1.11, b'Fundo')], default=1, verbose_name=b'Factor PM10'),
        ),
    ]
