# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0016_auto_20160516_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='lcL_backgroud',
            new_name='lcL_background',
        ),
    ]
