# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0017_auto_20160516_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='lcL_background',
            field=models.ImageField(blank=True, null=True, upload_to=b'path', verbose_name=b'Imagem de Fundo'),
        ),
    ]
