# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0018_auto_20160516_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='lcL_background',
            field=models.ImageField(blank=True, null=True, upload_to=b'labqar', verbose_name=b'Imagem de Fundo'),
        ),
    ]
