# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0021_auto_20160518_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcm_token',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
