# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0022_auto_20160518_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcm_token',
            name='user',
        ),
        migrations.DeleteModel(
            name='Gcm_Token',
        ),
    ]
