# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0025_parametro_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro_local',
            name='par_nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametro_local',
            name='par_unidade_apresent',
            field=models.CharField(choices=[(b'ppm', b'ppm'), (b'ppb', b'ppb'), (b'U+00B5g/m3', b'U+00B5g/m3')], default=b'U+00B5g/m3', max_length=50, null=True, verbose_name=b'Unidade de apresentacao'),
        ),
    ]
