# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0029_auto_20160519_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro_local',
            name='par_unidade_apresent',
            field=models.CharField(choices=[('\xb5g/m3', '\xb5g/m3'), (b'ppm', b'ppm'), (b'ppb', b'ppb'), (b'W/m2', b'W/m2'), (b'mm', b'mm'), (b'mBar', b'mBar'), (b'm/s', b'm/s'), (b'\xc2\xbaC', b'\xc2\xbaC'), (b'\xc2\xbaN', b'\xc2\xbaN'), (b'%', b'%')], default='\xb5g/m3', max_length=50, null=True, verbose_name=b'Unidade de apresentacao'),
        ),
    ]
