# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0031_auto_20160519_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas_concentracao',
            name='alr_parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labqar.Parametro_Local', verbose_name=b'Parametro Associado'),
        ),
    ]
