# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0032_auto_20160519_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertas_concentracao',
            name='alr_valor_min',
        ),
    ]
