# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0033_remove_alertas_concentracao_alr_valor_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='est_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labqar.Estacao', verbose_name=b'Estacao'),
        ),
    ]
