# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0035_auto_20160614_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Alertas',
            fields=[
                ('his_id', models.AutoField(primary_key=True, serialize=False)),
                ('his_alerta', models.CharField(max_length=255)),
                ('his_hora', models.CharField(max_length=255)),
                ('his_codigo', models.IntegerField()),
                ('his_campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labqar.Periodo_Campanha')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Hist\xf3rico Alertas',
            },
        ),
        migrations.AlterModelOptions(
            name='dados',
            options={'ordering': ['-dad_data'], 'verbose_name': 'Dados', 'verbose_name_plural': 'Dados'},
        ),
    ]
