# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0036_auto_20160620_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico_alertas',
            options={'ordering': ['-his_data'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Hist\xf3rico Alertas'},
        ),
        migrations.RenameField(
            model_name='historico_alertas',
            old_name='his_hora',
            new_name='his_data',
        ),
    ]
