# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0037_auto_20160620_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico_alertas',
            name='his_campanha',
        ),
    ]
