# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0038_remove_historico_alertas_his_campanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_alertas',
            name='his_campanha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labqar.Periodo_Campanha'),
        ),
    ]
