# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0040_auto_20160621_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro_local',
            name='par_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
