# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0042_auto_20160621_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas_concentracao',
            name='alr_disabled',
            field=models.BooleanField(default=False, verbose_name=b'Desativar notifica\xc3\xa7\xc3\xb5es para clientes'),
        ),
    ]
