# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0043_alertas_concentracao_alr_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_alertas',
            name='his_disabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
