# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labqar', '0044_historico_alertas_his_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='lcL_background',
            new_name='lcl_background',
        ),
    ]
